var countryNames = {
  short: {
    oecd: "OECD",
    afg: "Afghanistan",
    alb: "Albania",
    dza: "Algeria",
    asm: "American Samoa",
    and: "Andorra",
    ago: "Angola",
    aia: "Anguilla",
    atg: "Antigua and Barbuda",
    arg: "Argentina",
    arm: "Armenia",
    abw: "Aruba",
    aus: "Australia",
    aut: "Austria",
    aze: "Azerbaijan",
    bhs: "Bahamas",
    bhr: "Bahrain",
    bgd: "Bangladesh",
    brb: "Barbados",
    blr: "Belarus",
    bel: "Belgium",
    blz: "Belize",
    ben: "Benin",
    bmu: "Bermuda",
    btn: "Bhutan",
    bol: "Bolivia",
    bih: "Bosnia and Herzegovina",
    bwa: "Botswana",
    bvt: "Bouvet Island",
    bra: "Brazil",
    iot: "British Indian Ocean Territory",
    vgb: "British Virgin Islands",
    brn: "Brunei Darussalam",
    bgr: "Bulgaria",
    bfa: "Burkina Faso",
    bdi: "Burundi",
    cpv: "Cabo Verde",
    khm: "Cambodia",
    cmr: "Cameroon",
    can: "Canada",
    cym: "Cayman Islands",
    caf: "Central African Republic",
    tcd: "Chad",
    chl: "Chile",
    chn: "China",
    cxr: "Christmas Island",
    col: "Colombia",
    com: "Comoros",
    cog: "Congo",
    cok: "Cook Islands",
    cri: "Costa Rica",
    hrv: "Croatia",
    cub: "Cuba",
    cuw: "Cura\u00e7ao",
    cyp: "Cyprus",
    cze: "Czech Republic",
    civ: "C\u00f4te d'Ivoire",
    prk: "DPRK",
    cod: "DRC",
    dnk: "Denmark",
    dji: "Djibouti",
    dma: "Dominica",
    dom: "Dominican Republic",
    ecu: "Ecuador",
    egy: "Egypt",
    slv: "El Salvador",
    gnq: "Equatorial Guinea",
    eri: "Eritrea",
    est: "Estonia",
    swz: "Eswatini",
    eth: "Ethiopia",
    mkd: "FYROM",
    flk: "Falkland Islands (Malvinas)",
    fro: "Faroe Islands",
    fji: "Fiji",
    fin: "Finland",
    fra: "France",
    pyf: "French Polynesia",
    atf: "French Southern and Antarctic Lands",
    gab: "Gabon",
    gmb: "Gambia",
    geo: "Georgia",
    deu: "Germany",
    gha: "Ghana",
    gib: "Gibraltar",
    grc: "Greece",
    grl: "Greenland",
    grd: "Grenada",
    gum: "Guam",
    gtm: "Guatemala",
    ggy: "Guernsey",
    gin: "Guinea",
    gnb: "Guinea-Bissau",
    guy: "Guyana",
    hmd: "HIMI",
    hti: "Haiti",
    hnd: "Honduras",
    hkg: "Hong Kong",
    hun: "Hungary",
    isl: "Iceland",
    ind: "India",
    idn: "Indonesia",
    irn: "Iran",
    irq: "Iraq",
    irl: "Ireland",
    imn: "Isle of Man",
    isr: "Israel",
    ita: "Italy",
    jam: "Jamaica",
    jpn: "Japan",
    jey: "Jersey",
    jor: "Jordan",
    kaz: "Kazakhstan",
    ken: "Kenya",
    kir: "Kiribati",
    kor: "Korea",
    kos: "Kosovo",
    kwt: "Kuwait",
    kgz: "Kyrgyzstan",
    lao: "Lao PDR",
    lva: "Latvia",
    lbn: "Lebanon",
    lso: "Lesotho",
    lbr: "Liberia",
    lby: "Libya",
    lie: "Liechtenstein",
    ltu: "Lithuania",
    lux: "Luxembourg",
    mac: "Macau, China",
    mdg: "Madagascar",
    mwi: "Malawi",
    mys: "Malaysia",
    mdv: "Maldives",
    mli: "Mali",
    mlt: "Malta",
    mhl: "Marshall Islands",
    mrt: "Mauritania",
    mus: "Mauritius",
    myt: "Mayotte",
    mex: "Mexico",
    fsm: "Micronesia",
    mda: "Moldova",
    mco: "Monaco",
    mng: "Mongolia",
    mne: "Montenegro",
    msr: "Montserrat",
    mar: "Morocco",
    moz: "Mozambique",
    mmr: "Myanmar",
    nam: "Namibia",
    nru: "Nauru",
    npl: "Nepal",
    nld: "Netherlands",
    ant: "Netherlands Antilles",
    ncl: "New Caledonia",
    nzl: "New Zealand",
    nic: "Nicaragua",
    ner: "Niger",
    nga: "Nigeria",
    niu: "Niue",
    nfk: "Norfolk Island",
    mnp: "Northern Mariana Islands",
    nor: "Norway",
    omn: "Oman",
    pak: "Pakistan",
    plw: "Palau",
    pan: "Panama",
    png: "Papua New Guinea",
    pry: "Paraguay",
    per: "Peru",
    phl: "Philippines",
    pcn: "Pitcairn",
    pol: "Poland",
    prt: "Portugal",
    pri: "Puerto Rico",
    qat: "Qatar",
    rou: "Romania",
    rus: "Russia",
    rwa: "Rwanda",
    shn: "Saint Helena",
    kna: "Saint Kitts and Nevis",
    lca: "Saint Lucia",
    vct: "Saint Vincent and the Grenadines",
    wsm: "Samoa",
    smr: "San Marino",
    stp: "Sao Tome and Principe",
    sau: "Saudi Arabia",
    sen: "Senegal",
    srb: "Serbia",
    syc: "Seychelles",
    sle: "Sierra Leone",
    sgp: "Singapore",
    sxm: "Sint Maarten",
    svk: "Slovakia",
    svn: "Slovenia",
    slb: "Solomon Islands",
    som: "Somalia",
    zaf: "South Africa",
    sgs: "South Georgia and the South Sandwich Islands",
    ssd: "South Sudan",
    esp: "Spain",
    lka: "Sri Lanka",
    sdn: "Sudan",
    sur: "Suriname",
    swe: "Sweden",
    che: "Switzerland",
    syr: "Syria",
    twn: "Chinese Taipei",
    tjk: "Tajikistan",
    tza: "Tanzania",
    tha: "Thailand",
    tls: "Timor-Leste",
    tgo: "Togo",
    tkl: "Tokelau",
    ton: "Tonga",
    tto: "Trinidad and Tobago",
    tun: "Tunisia",
    tur: "Turkey",
    tkm: "Turkmenistan",
    tca: "Turks and Caicos Islands",
    tuv: "Tuvalu",
    uga: "Uganda",
    ukr: "Ukraine",
    are: "United Arab Emirates",
    gbr: "United Kingdom",
    usa: "United States",
    umi: "United States Minor Outlying Islands",
    vir: "United States Virgin Islands",
    ury: "Uruguay",
    uzb: "Uzbekistan",
    vut: "Vanuatu",
    ven: "Venezuela",
    vnm: "Viet Nam",
    wlf: "Wallis and Futuna",
    pse: "West Bank and Gaza Strip",
    esh: "Western Sahara \u008e",
    yem: "Yemen",
    zmb: "Zambia",
    zwe: "Zimbabwe",
    r12: "Offshore financial centres",
    "4a": "Non-euro area EU institutions",
    "9a": "Non-EU international organisations",
    eu: "European Union",
    eur: "Euro area",
  },
  long: {
    oecd: "OECD",
    afg: "Afghanistan",
    alb: "Albania",
    dza: "Algeria",
    asm: "American Samoa",
    and: "Andorra",
    ago: "Angola",
    aia: "Anguilla",
    atg: "Antigua and Barbuda",
    arg: "Argentina",
    arm: "Armenia",
    abw: "Aruba",
    aus: "Australia",
    aut: "Austria",
    aze: "Azerbaijan",
    bhs: "Bahamas",
    bhr: "Bahrain",
    bgd: "Bangladesh",
    brb: "Barbados",
    blr: "Belarus",
    bel: "Belgium",
    blz: "Belize",
    ben: "Benin",
    bmu: "Bermuda",
    btn: "Bhutan",
    bol: "Bolivia",
    bih: "Bosnia and Herzegovina",
    bwa: "Botswana",
    bvt: "Bouvet Island",
    bra: "Brazil",
    iot: "British Indian Ocean Territory",
    vgb: "British Virgin Islands",
    brn: "Brunei Darussalam",
    bgr: "Bulgaria",
    bfa: "Burkina Faso",
    bdi: "Burundi",
    cpv: "Cabo Verde",
    khm: "Cambodia",
    cmr: "Cameroon",
    can: "Canada",
    cym: "Cayman Islands",
    caf: "Central African Republic",
    tcd: "Chad",
    chl: "Chile",
    chn: "China",
    cxr: "Christmas Island",
    col: "Colombia",
    com: "Comoros",
    cog: "Congo",
    cok: "Cook Islands",
    cri: "Costa Rica",
    hrv: "Croatia",
    cub: "Cuba",
    cuw: "Cura\u00e7ao",
    cyp: "Cyprus",
    cze: "Czech Republic",
    civ: "C\u00f4te d'Ivoire",
    prk: "DPRK",
    cod: "DRC",
    dnk: "Denmark",
    dji: "Djibouti",
    dma: "Dominica",
    dom: "Dominican Republic",
    ecu: "Ecuador",
    egy: "Egypt",
    slv: "El Salvador",
    gnq: "Equatorial Guinea",
    eri: "Eritrea",
    est: "Estonia",
    swz: "Eswatini",
    eth: "Ethiopia",
    mkd: "FYROM",
    flk: "Falkland Islands (Malvinas)",
    fro: "Faroe Islands",
    fji: "Fiji",
    fin: "Finland",
    fra: "France",
    pyf: "French Polynesia",
    atf: "French Southern and Antarctic Lands",
    gab: "Gabon",
    gmb: "Gambia",
    geo: "Georgia",
    deu: "Germany",
    gha: "Ghana",
    gib: "Gibraltar",
    grc: "Greece",
    grl: "Greenland",
    grd: "Grenada",
    gum: "Guam",
    gtm: "Guatemala",
    ggy: "Guernsey",
    gin: "Guinea",
    gnb: "Guinea-Bissau",
    guy: "Guyana",
    hmd: "HIMI",
    hti: "Haiti",
    hnd: "Honduras",
    hkg: "Hong Kong",
    hun: "Hungary",
    isl: "Iceland",
    ind: "India",
    idn: "Indonesia",
    irn: "Iran",
    irq: "Iraq",
    irl: "Ireland",
    imn: "Isle of Man",
    isr: "Israel",
    ita: "Italy",
    jam: "Jamaica",
    jpn: "Japan",
    jey: "Jersey",
    jor: "Jordan",
    kaz: "Kazakhstan",
    ken: "Kenya",
    kir: "Kiribati",
    kor: "Korea",
    kos: "Kosovo",
    kwt: "Kuwait",
    kgz: "Kyrgyzstan",
    lao: "Lao PDR",
    lva: "Latvia",
    lbn: "Lebanon",
    lso: "Lesotho",
    lbr: "Liberia",
    lby: "Libya",
    lie: "Liechtenstein",
    ltu: "Lithuania",
    lux: "Luxembourg",
    mac: "Macau, China",
    mdg: "Madagascar",
    mwi: "Malawi",
    mys: "Malaysia",
    mdv: "Maldives",
    mli: "Mali",
    mlt: "Malta",
    mhl: "Marshall Islands",
    mrt: "Mauritania",
    mus: "Mauritius",
    myt: "Mayotte",
    mex: "Mexico",
    fsm: "Micronesia",
    mda: "Moldova",
    mco: "Monaco",
    mng: "Mongolia",
    mne: "Montenegro",
    msr: "Montserrat",
    mar: "Morocco",
    moz: "Mozambique",
    mmr: "Myanmar",
    nam: "Namibia",
    nru: "Nauru",
    npl: "Nepal",
    nld: "Netherlands",
    ant: "Netherlands Antilles",
    ncl: "New Caledonia",
    nzl: "New Zealand",
    nic: "Nicaragua",
    ner: "Niger",
    nga: "Nigeria",
    niu: "Niue",
    nfk: "Norfolk Island",
    mnp: "Northern Mariana Islands",
    nor: "Norway",
    omn: "Oman",
    pak: "Pakistan",
    plw: "Palau",
    pan: "Panama",
    png: "Papua New Guinea",
    pry: "Paraguay",
    per: "Peru",
    phl: "Philippines",
    pcn: "Pitcairn",
    pol: "Poland",
    prt: "Portugal",
    pri: "Puerto Rico",
    qat: "Qatar",
    rou: "Romania",
    rus: "Russia",
    rwa: "Rwanda",
    shn: "Saint Helena",
    kna: "Saint Kitts and Nevis",
    lca: "Saint Lucia",
    vct: "Saint Vincent and the Grenadines",
    wsm: "Samoa",
    smr: "San Marino",
    stp: "Sao Tome and Principe",
    sau: "Saudi Arabia",
    sen: "Senegal",
    srb: "Serbia",
    syc: "Seychelles",
    sle: "Sierra Leone",
    sgp: "Singapore",
    sxm: "Sint Maarten",
    svk: "Slovakia",
    svn: "Slovenia",
    slb: "Solomon Islands",
    som: "Somalia",
    zaf: "South Africa",
    sgs: "South Georgia and the South Sandwich Islands",
    ssd: "South Sudan",
    esp: "Spain",
    lka: "Sri Lanka",
    sdn: "Sudan",
    sur: "Suriname",
    swe: "Sweden",
    che: "Switzerland",
    syr: "Syria",
    twn: "Chinese Taipei",
    tjk: "Tajikistan",
    tza: "Tanzania",
    tha: "Thailand",
    tls: "Timor-Leste",
    tgo: "Togo",
    tkl: "Tokelau",
    ton: "Tonga",
    tto: "Trinidad and Tobago",
    tun: "Tunisia",
    tur: "Turkey",
    tkm: "Turkmenistan",
    tca: "Turks and Caicos Islands",
    tuv: "Tuvalu",
    uga: "Uganda",
    ukr: "Ukraine",
    are: "United Arab Emirates",
    gbr: "United Kingdom",
    usa: "United States",
    umi: "United States Minor Outlying Islands",
    vir: "United States Virgin Islands",
    ury: "Uruguay",
    uzb: "Uzbekistan",
    vut: "Vanuatu",
    ven: "Venezuela",
    vnm: "Viet Nam",
    wlf: "Wallis and Futuna",
    pse: "West Bank and Gaza Strip",
    esh: "Western Sahara \u008e",
    yem: "Yemen",
    zmb: "Zambia",
    zwe: "Zimbabwe",
    r12: "Offshore financial centres",
    "4a": "European Union institutions excluding euro area institutions",
    "9a": "International organisations excluding European Union institutions",
    eu: "European Union",
    eur: "Euro area",
  },
  order: [
    "oecd",
    "afg",
    "alb",
    "dza",
    "asm",
    "and",
    "ago",
    "aia",
    "atg",
    "arg",
    "arm",
    "abw",
    "aus",
    "aut",
    "aze",
    "bhs",
    "bhr",
    "bgd",
    "brb",
    "blr",
    "bel",
    "blz",
    "ben",
    "bmu",
    "btn",
    "bol",
    "bih",
    "bwa",
    "bvt",
    "bra",
    "iot",
    "vgb",
    "brn",
    "bgr",
    "bfa",
    "bdi",
    "cpv",
    "khm",
    "cmr",
    "can",
    "cym",
    "caf",
    "tcd",
    "chl",
    "chn",
    "cxr",
    "col",
    "com",
    "cog",
    "cok",
    "cri",
    "hrv",
    "cub",
    "cuw",
    "cyp",
    "cze",
    "civ",
    "prk",
    "cod",
    "dnk",
    "dji",
    "dma",
    "dom",
    "ecu",
    "egy",
    "slv",
    "gnq",
    "eri",
    "est",
    "swz",
    "eth",
    "mkd",
    "flk",
    "fro",
    "fji",
    "fin",
    "fra",
    "pyf",
    "atf",
    "gab",
    "gmb",
    "geo",
    "deu",
    "gha",
    "gib",
    "grc",
    "grl",
    "grd",
    "gum",
    "gtm",
    "ggy",
    "gin",
    "gnb",
    "guy",
    "hmd",
    "hti",
    "hnd",
    "hkg",
    "hun",
    "isl",
    "ind",
    "idn",
    "irn",
    "irq",
    "irl",
    "imn",
    "isr",
    "ita",
    "jam",
    "jpn",
    "jey",
    "jor",
    "kaz",
    "ken",
    "kir",
    "kor",
    "kos",
    "kwt",
    "kgz",
    "lao",
    "lva",
    "lbn",
    "lso",
    "lbr",
    "lby",
    "lie",
    "ltu",
    "lux",
    "mac",
    "mdg",
    "mwi",
    "mys",
    "mdv",
    "mli",
    "mlt",
    "mhl",
    "mrt",
    "mus",
    "myt",
    "mex",
    "fsm",
    "mda",
    "mco",
    "mng",
    "mne",
    "msr",
    "mar",
    "moz",
    "mmr",
    "nam",
    "nru",
    "npl",
    "nld",
    "ant",
    "ncl",
    "nzl",
    "nic",
    "ner",
    "nga",
    "niu",
    "nfk",
    "mnp",
    "nor",
    "omn",
    "pak",
    "plw",
    "pan",
    "png",
    "pry",
    "per",
    "phl",
    "pcn",
    "pol",
    "prt",
    "pri",
    "qat",
    "rou",
    "rus",
    "rwa",
    "shn",
    "kna",
    "lca",
    "vct",
    "wsm",
    "smr",
    "stp",
    "sau",
    "sen",
    "srb",
    "syc",
    "sle",
    "sgp",
    "sxm",
    "svk",
    "svn",
    "slb",
    "som",
    "zaf",
    "sgs",
    "ssd",
    "esp",
    "lka",
    "sdn",
    "sur",
    "swe",
    "che",
    "syr",
    "twn",
    "tjk",
    "tza",
    "tha",
    "tls",
    "tgo",
    "tkl",
    "ton",
    "tto",
    "tun",
    "tur",
    "tkm",
    "tca",
    "tuv",
    "uga",
    "ukr",
    "are",
    "gbr",
    "usa",
    "umi",
    "vir",
    "ury",
    "uzb",
    "vut",
    "ven",
    "vnm",
    "wlf",
    "pse",
    "esh",
    "yem",
    "zmb",
    "zwe",
    "r12",
    "4a",
    "9a",
    "eu",
    "eur",
  ],
};
